import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:workmanager/workmanager.dart';

import 'app.dart';
import 'core/constants/super_admin_config.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((taskName, inputData) async {
    if (taskName == 'sevakai_location_update') {
      // TODO: Implement in Phase 4 (Location Feature)
      // LocationService().updateVolunteerLocation();
    }
    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await dotenv.load(fileName: ".env");

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await Workmanager().initialize(
    callbackDispatcher,
  );

  // Load Super Admin email list from Firestore (seeds defaults on first run)
  await SuperAdminConfig().initialize();

  runApp(
    const ProviderScope(
      child: SevakApp(),
    ),
  );
}
