import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:workmanager/workmanager.dart';

import 'app.dart';
import 'core/constants/super_admin_config.dart';
import 'features/location/data/location_service.dart';
import 'features/tasks/data/services/task_notification_service.dart';
// import 'firebase_options.dart'; // Generated by flutterfire configure

@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((taskName, inputData) async {
    if (taskName == 'sevakai_location_update') {
      final uid = FirebaseAuth.instance.currentUser?.uid;
      if (uid != null) {
        await LocationService().updateVolunteerLocation(uid, force: true);
      }
    }
    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await dotenv.load(fileName: ".env");

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  await Workmanager().initialize(
    callbackDispatcher,
  );
  
  // Register background location update (every 15 mins)
  await Workmanager().registerPeriodicTask(
    '1',
    'sevakai_location_update',
    frequency: const Duration(minutes: 15),
    constraints: Constraints(
      networkType: NetworkType.connected,
    ),
  );

  // Initialize local notifications (Phase 4F)
  await TaskNotificationService.initialize();

  // Load Super Admin email list from Firestore (seeds defaults on first run)
  await SuperAdminConfig().initialize();

  runApp(
    const ProviderScope(
      child: SevakApp(),
    ),
  );
}
